version: '3.8'

services:
  mysql:
    image: mysql:8.0.26
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: e_commerce
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
  

  backend:
    build: ./ecommerce
    container_name: backend-service
    depends_on:
      - mysql
    ports:
      - "9090:9090"
    volumes:
      - ./ecommerce:/app

  frontend:
    build: ./EcommerceProyectFront
    container_name: frontend-service
    ports:
      - "4200:4200"
    volumes:
      - ./EcommerceProyectFront:/app

volumes:
  mysql-data:
