name: CI/CD Pipeline  # Nombre de la canalización

on:  # Evento que activa la ejecución de la canalización
  push:  # Se activa cuando se realiza un push
    branches:  # Se especifica la rama que activa la canalización
      - main  # Se especifica la rama 'main'

jobs:  # Definición de los trabajos que se ejecutarán en la canalización
  build-and-deploy:  # Trabajo para construir y desplegar
    runs-on: ubuntu-latest  # Entorno en el que se ejecutará el trabajo (en este caso, Ubuntu)

    steps:  # Definición de los pasos del trabajo
      - name: Checkout code  # Paso para obtener el código del repositorio
        uses: actions/checkout@v2  # Se utiliza la acción 'checkout' para obtener el código del repositorio

      - name: Increment version  # Paso para incrementar automáticamente la versión del proyecto
        run: npm version patch --force  # Incrementa el número de versión de forma automática

      - name: Generate changelog  # Paso para generar el registro de cambios
        run: echo "Version ${{ steps.versioning.outputs['version'] }}" > CHANGELOG.md  # Genera el registro de cambios basado en la versión actual

      - name: Commit version and changelog  # Paso para realizar un commit con los cambios en la versión y el registro de cambios
        run: |
          git config --local user.email "$(git config user.email)"  # Utiliza el correo electrónico local del usuario de Git
          git config --local user.name "$(git config user.name)"  # Utiliza el nombre local del usuario de Git
          git add .  # Agrega todos los archivos al área de preparación
          git commit -m "Bump version and update changelog"  # Realiza un commit con el mensaje especificado
          git push origin main  # Empuja los cambios al repositorio remoto en la rama main

